accounts/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('orders/', views.orders, name='orders'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('passwordChangeDone/', TemplateView.as_view(template_name='accounts/passwordChangeDone.html'), name='passwordChangeDone'),]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    # path('', views.index, name='cart.index'),
    # path('<int:id>/add/', views.add, name='cart.add'),
    # path('clear/', views.clear, name='cart.clear'),
    # path('purchase/', views.purchase, name='cart.purchase'),

    path('', views.index, name='index'),
    path('<int:id>/add/', views.add, name='add'),
    path('clear/', views.clear, name='clear'),
    path('purchase/', views.purchase, name='purchase'),
]

home/urls.py
from django.urls import path
from . import views

#path method takes in the:
# 1) the route to be accessed,
# 2) the view method from views.py,
# 3) name given to the path to uniquely distinguish in the django project
app_name = 'home'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('about', views.about, name = 'about' )
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('show/<int:id>/', views.show, name='show'),
    path('<int:id>/review/create', views.create_review, name='create_review'),
    path('<int:id>/review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:id>/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

moviesstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Movie (models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='movie_images/',  blank=True, null=True)

    def __str__(self):
        return f"{self.id} - {self.name}"

class Review (models.Model):
    id = models.AutoField(primary_key=True)
    comment = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} - {self.movie.name}"

movies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review


# Create your views here.
def index (request):
    search_term = request.GET.get('search')
    if search_term:
        movies = Movie.objects.filter(name__icontains = search_term)
    else:
        movies = Movie.objects.all()
    template_data = {}
    template_data['title'] = 'Movies'
    template_data['movies'] = movies
    return render(request, 'movies/index.html', {'template_data': template_data} )


def show(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=movie)
    template_data = {}
    template_data['title'] = movie.name
    template_data['movie'] = movie
    template_data['reviews'] = reviews
    return render(request, 'movies/show.html', {'template_data': template_data})

@login_required
def create_review(request, id):
    if request.method == 'POST' and request.POST['comment'] != '':
        movie = Movie.objects.get(id=id)
        review = Review()
        review.comment = request.POST['comment']
        review.movie = movie
        review.user = request.user
        review.save()
        return redirect('movies:show', id=id)
    else:
        return redirect('movies:show', id=id)

@login_required
def edit_review(request, id, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user != review.user:
        return redirect('movies:show', id=id)
    if request.method == 'GET':
        template_data = {}
        template_data['title'] = 'Edit Review'
        template_data['review'] = review
        return render(request, 'movies/edit_review.html',
            {'template_data': template_data})
    elif request.method == 'POST' and request.POST['comment'] != '':
        review = Review.objects.get(id=review_id)
        review.comment = request.POST['comment']
        review.save()
        return redirect('movies:show', id=id)
    else:
        return redirect('movies:show', id=id)

@login_required
def delete_review(request, id, review_id):
    review = get_object_or_404(Review, id=review_id, user=request.user)
    review.delete()
    return redirect('movies:show', id=id)

movies/templates/movies/edit_review.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Movies Store 1</title>
        <!-- Bootstrap 5 CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    </head>
<body>
    {% block content %}
    <div class="p-3">
      <div class="container">
        <div class="row mt-3">
          <div class="col mx-auto mb-3">
            <h2>Edit Review</h2>
            <hr />
            <form method="POST">
              {% csrf_token %}
              <p>
                <label for="comment">Comment:</label>
                <textarea name="comment" required
                class="form-control" id="comment">{{template_data.review.comment }}</textarea>
              </p>
              <div class="text-start">
                <button type="submit"
                  class="btn bg-dark text-white">Edit Review
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock content %}
</body>
</html>

movies/templates/movies/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ template_data.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
<body>
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #000000 !important;">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <!-- Logo -->
            <div class="d-flex align-items-center">
                <a class="navbar-brand ps-3" href="{% url 'home:index' %}">
                    <img src="{% static 'home/images/logo.png' %}" width="130" height="40" alt="Movies Store Logo">
                </a>
            </div>
            <!-- Navbar Toggler & Links -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Right Container: Navbar Links -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
{#                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:index' %}">Home</a></li>#}
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:about' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'movies:index' %}">Movies</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:orders' %}">Orders</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'cart:index' %}">Cart</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
            </div>

        </div>
    </nav>

    <div class="container mx-auto mb-3" style="padding-top: 100px;">
        <div class="container-fluid">
            <div class="row justify-content-center mb-4">
                <div class="col-lg-6 col-md-8">
                    <form method="GET">
                        <div class="input-group">
                            <div class="input-group-text">Search</div>
                            <input type="text" class="form-control" name="search">
                            <button class="btn bg-dark text-white" type="submit">Search</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row justify-content-center">
                {% for movie in template_data.movies %}
                  <div class="col-md-4 col-lg-3 mb-2 mx-2">
                    <div class="p-2 card align-items-center pt-4">
                      <img src="{{ movie.image.url }}"
                        class="card-img-top rounded" alt="Image of Movie {{movie.name}}">
                      <div class="card-body text-center">
                        <a href="{% url 'movies:show' id=movie.id %}"
                          class="btn bg-dark text-white">
                          {{ movie.name }}
                        </a>
                      </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

movies/templates/movies/show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Movies Store 1</title>
        <!-- Bootstrap 5 CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #000000 !important;">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <!-- Logo -->
                <div class="d-flex align-items-center">
                    <a class="navbar-brand ps-3" href="{% url 'home:index' %}">
                        <img src="{% static 'home/images/logo.png' %}" width="130" height="40" alt="Movies Store Logo">
                    </a>
                </div>
                <!-- Navbar Toggler & Links -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Right Container: Navbar Links -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
    {#                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:index' %}">Home</a></li>#}
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'movies:index' %}">Movies</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:orders' %}">Orders</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'cart:index' %}">Cart</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                </div>

            </div>
        </nav>
    <div  class="d-flex" style="padding-top: 100px;">
        <div>
            <div class="col-md-6 mx-auto mb-3">
                <h2>{{ template_data.movie.name }}</h2>
                <hr />
                <p><b>Description:</b> {{template_data.movie.description}}</p>
                <p><b>Price:</b> ${{template_data.movie.price}}</p>
                <p class="card-text">
                  <form method="post" action="{% url 'cart:add' id=template_data.movie.id %}">
                    <div class="row">
                      {% csrf_token %}
                      <div class="col-auto">
                        <div class="input-group col-auto">
                          <div class="input-group-text">Quantity</div>
                          <input type="number" min="1" max="10" class="form-control quantity-input" name="quantity" value="1">
                        </div>
                      </div>
                      <div class="col-auto">
                        <button class="btn bg-dark text-white" type="submit">Add to cart</button>
                      </div>
                    </div>
                  </form>
                </p>

                <h2>Reviews</h2>
                <hr />
                <ul class="list-group">
                  {% for review in template_data.reviews %}
                  <li class="list-group-item pb-3 pt-3">
                    <h5 class="card-title">
                      Review by {{ review.user.username }}
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">
                      {{ review.date }}
                    </h6>
                    <p class="card-text">{{ review.comment }}</p>
                     {% if user.is_authenticated and user == review.user %}
                    <a class="btn btn-primary" href="{% url 'movies:edit_review' id=template_data.movie.id review_id=review.id %}">
                        Edit
                    </a>
                    <a class="btn btn-danger"
                      href="{% url 'movies:delete_review' id=template_data.movie.id review_id=review.id %}">Delete
                    </a>
                    {% endif %}
                  </li>
                  {% endfor %}
                </ul>
                {% if user.is_authenticated %}
                    <div class="container mt-4">
                      <div class="row justify-content-center">
                        <div class="col-12">
                          <div class="card shadow p-3 mb-4 rounded">
                            <div class="card-body">
                              <b class="text-start">Create a review</b>
                                <br />
                                <br />
                              <form method="POST" action= "{% url 'movies:create_review' id=template_data.movie.id %}">
                                {% csrf_token %}
                                <p>
                                  <label for="comment">Comment:</label>
                                  <textarea name="comment" required class="form-control" id="comment">

                                  </textarea>
                                </p>
                                <div class="text-center">
                                  <button type="submit"
                                    class="btn bg-dark text-white">
                                    Add Review
                                  </button>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                {% endif %}
              </div>
        </div>
        <div class="col-md-6 mx-auto mb-3 text-center">
            <img src="{{ template_data.movie.image.url }}"
              class="rounded w-60 img-fluid"  alt="Image of Movie {{template_data.title}}"/>
        </div>
    </div>
    </body>
</html>