accounts/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('orders/', views.orders, name='orders'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('passwordChangeDone/', TemplateView.as_view(template_name='accounts/passwordChangeDone.html'), name='passwordChangeDone'),]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    # path('', views.index, name='cart.index'),
    # path('<int:id>/add/', views.add, name='cart.add'),
    # path('clear/', views.clear, name='cart.clear'),
    # path('purchase/', views.purchase, name='cart.purchase'),

    path('', views.index, name='index'),
    path('<int:id>/add/', views.add, name='add'),
    path('clear/', views.clear, name='clear'),
    path('purchase/', views.purchase, name='purchase'),
]

home/urls.py
from django.urls import path
from . import views

#path method takes in the:
# 1) the route to be accessed,
# 2) the view method from views.py,
# 3) name given to the path to uniquely distinguish in the django project
app_name = 'home'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('about', views.about, name = 'about' )
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('show/<int:id>/', views.show, name='show'),
    path('<int:id>/review/create', views.create_review, name='create_review'),
    path('<int:id>/review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:id>/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

moviesstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesstore/templates/base.html
{% load static %}
<!DOCTYPE html>
  {% load static %}
  <head>
    <title>{{ template_data.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charset="UTF-8">

  </head>

  <body>

    <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #000000 !important;">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <!-- Logo -->
                <div class="d-flex align-items-center">
                    <a class="navbar-brand ps-3" href="{% url 'home:index' %}">
                        <img src="{% static 'home/images/logo.png' %}" width="130" height="40" alt="Movies Store Logo">
                    </a>
                </div>
                <!-- Navbar Toggler & Links -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Right Container: Navbar Links -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
    {#                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:index' %}">Home</a></li>#}
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'movies:index' %}">Movies</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:orders'%}">Orders</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'cart:index' %}">Cart</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                </div>

            </div>
        </nav>


    <div>
      {% block content %}
      {% endblock content %}
    </div>

  </body>
</html>

moviesstore/templates/dase.html
{% load static %}
<!DOCTYPE html>
  {% load static %}
  <head>
    <title>{{ template_data.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charset="UTF-8">

  </head>

  <body>

    <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #000000 !important;">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <!-- Logo -->
                <div class="d-flex align-items-center">
                    <a class="navbar-brand ps-3" href="{% url 'home:index' %}">
                        <img src="{% static 'home/images/logo.png' %}" width="130" height="40" alt="Movies Store Logo">
                    </a>
                </div>
                <!-- Navbar Toggler & Links -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Right Container: Navbar Links -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
    {#                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:index' %}">Home</a></li>#}
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'movies:index' %}">Movies</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:orders'%}">Orders</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'cart:index' %}">Cart</a></li>
                        <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:login' %}">Login</a></li>
                    </ul>
                </div>

            </div>
        </nav>


    <div>
      {% block content %}
      {% endblock content %}
    </div>

  </body>
</html>