accounts/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('orders/', views.orders, name='orders'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('passwordChangeDone/', TemplateView.as_view(template_name='accounts/passwordChangeDone.html'), name='passwordChangeDone'),]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    # path('', views.index, name='cart.index'),
    # path('<int:id>/add/', views.add, name='cart.add'),
    # path('clear/', views.clear, name='cart.clear'),
    # path('purchase/', views.purchase, name='cart.purchase'),

    path('', views.index, name='index'),
    path('<int:id>/add/', views.add, name='add'),
    path('clear/', views.clear, name='clear'),
    path('purchase/', views.purchase, name='purchase'),
]

moviesstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from movies.models import Movie

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    total = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + ' - ' + self.user.username

class Item(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.IntegerField()
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + ' - ' + self.movie.name

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.utils import ErrorList
from django.utils.safestring import mark_safe
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password

class CustomErrorList(ErrorList):
    def __str__(self):
        if not self:
            return ''
        return mark_safe(''.join([f'<div class="alert alert-danger" role="alert">{e}</div>' for e in self]))

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs.update({'class': 'form-control'})

class CustomPasswordChangeForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    old_password = forms.CharField(widget=forms.PasswordInput, required=True, label='Old Password')
    new_password1 = forms.CharField(widget=forms.PasswordInput, required=True, label='New Password')
    new_password2 = forms.CharField(widget=forms.PasswordInput, required=True, label = 'Confirm New Password')

    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'old_password', 'new_password1', 'new_password2']:
            self.fields[fieldname].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        old_password = cleaned_data.get('old_password')
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            self.add_error('new_password1', 'The new passwords do not match.')

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            self.add_error('username', 'User does not exist.')
            return cleaned_data

        if not check_password(old_password, user.password):
            self.add_error('old_password', 'The old password is incorrect.')

        return cleaned_data

    def save(self):
        username = self.cleaned_data.get('username')
        new_password = self.cleaned_data.get('new_password1')
        user = User.objects.get(username=username)
        user.set_password(new_password)
        user.save()

accounts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from .forms import CustomUserCreationForm, CustomErrorList, CustomPasswordChangeForm
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required

def login(request):
    template_data = {}
    template_data['title'] = 'Login'
    if request.method == 'GET':
        return render(request, 'accounts/login.html', {'template_data': template_data})
    elif request.method == 'POST':
        print(request.POST)
        user = authenticate(request, username = request.POST['username'], password = request.POST['password'])
        print(user)
        # if  user:
        #     template_data['error'] = 'The username or password is incorrect.'
        #     return render(request, 'accounts/login.html', {'template_data': template_data})
        # else:
        #     auth_login(request, user)
        #     return redirect('home:index')
        if user is None:  # Fix the condition
            template_data['error'] = 'The username or password is incorrect.'
            return render(request, 'accounts/login.html', {'template_data': template_data})
        else:
            auth_login(request, user)
            return redirect('home:index')

def signup(request):
    template_data = {}
    template_data['title'] = 'Sign Up'
    if request.method == 'GET':
        template_data['form'] = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'template_data': template_data})
    elif request.method == 'POST':
        form = CustomUserCreationForm(request.POST, error_class=CustomErrorList)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        else:
            template_data['form'] = form
            return render(request, 'accounts/signup.html',{'template_data': template_data})

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

@login_required
def orders(request):
    template_data = {}
    template_data['title'] = 'Orders'
    template_data['orders'] = request.user.order_set.all()
    return render(request, 'accounts/orders.html',
        {'template_data': template_data})

def changePassword(request):
    template_data = {}
    template_data['title'] = 'Change Password'

    if request.method == 'GET':
        template_data['form'] = CustomPasswordChangeForm()
        return render(request, 'accounts/changePassword.html', {'template_data': template_data})

    elif request.method == 'POST':
        form = CustomPasswordChangeForm(data=request.POST, error_class=CustomErrorList)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        else:
            template_data['form'] = form
            return render(request, 'accounts/changePassword.html', {'template_data': template_data})

accounts/templates/accounts/changePassword.html
{% extends 'dase.html' %}
{% block content %}
<div class="p-3 mt-4">
  <div class="container" style="padding-top: 100px;">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow p-3 mb-4 rounded">
          <div class="card-body">
            <h2>Change Password</h2>
            <hr />
            <form method="POST">
              {% csrf_token %}
              {{ template_data.form.as_p }}
              <button type="submit"
                class="btn bg-dark text-white">Change Password
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login - Movies Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        .login-container {
            display: flex;
            width: 100vw; /* Full viewport width */
            height: 100vh; /* Full viewport height */
        }

        .login-form {
            width: 50%; /* Half of the screen */
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 40px;
            background-color: #fff;
        }

        .login-content {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            max-width: 450px;
            width: 100%;
        }

        .login-content h2 {
            font-weight: bold;
            font-size: 2.5rem;
            text-align: center;
            margin-bottom: 20px;
        }

        .login-content p {
            font-size: 1.1rem;
            margin-bottom: 20px;
        }

        .login-content form {
            width: 100%;
        }

        .form-control {
            margin-bottom: 20px;
            border-radius: 8px;
            height: 50px;
            font-size: 1rem;
        }

        .btn-login {
            background-color: #000;
            color: #fff;
            width: 100%;
            padding: 15px;
            font-size: 1.1rem;
            border: none;
            border-radius: 8px;
        }

        .right-image {
            width: 50%;
            height: 100vh;
            background: url("https://wpcdn.us-east-1.vip.tn-cloud.net/www.pittsburghmagazine.com/content/uploads/data-import/1d64829b/oldcinema.jpg?etag=%225df745a4-be40c%22"), linear-gradient(45deg, red, blue);
            background-size: cover;
        }

        .create-account {
            font-size: 1rem;
            margin-top: 15px;
        }

        .create-account a {
            font-weight: bold;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <div class="login-form">
            <div class="login-content">
                <h2>Login to your Account</h2>
                <p>Welcome back! Login below</p>
                <form action="{% url 'accounts:login' %}" method="POST">
                    {% csrf_token %}
                    <p>
                        <label for="username">Username</label>
                        <input id="username" type="text"
                               name="username" required
                               autocomplete="username"
                               class="form-control">
                    </p>
                    <p>
                        <label for="password">Password</label>
                        <input id="password" type="password"
                               name="password" required
                               autocomplete="current-password"
                               class="form-control">
                    </p>
                    <button type="submit" class="btn btn-login">LOG IN</button>
                     {% if template_data.error %}
                        <div class="alert alert-danger my-2 text-center" role="alert">
                            {{ template_data.error }}
                        </div>
                    {% endif %}
                </form>

                <p class="create-account">Don't have an account? <a href="{% url 'accounts:signup' %}">Create an account</a></p>
                <p class="create-account">Want to change your password? <a href="{% url 'accounts:changePassword' %}">Change it here</a></p>
            </div>
        </div>
        <div class="right-image"></div>
    </div>
</body>
</html>

accounts/templates/accounts/orders.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
  <div class="container" style="padding-top: 80px;">
    <div class="row mt-3">
      <div class="col mx-auto mb-3">
        <h2>My Orders</h2>
        <hr />
        {% for order in template_data.orders %}
        <div class="card mb-4">
          <div class="card-header">
            Order #{{ order.id }}
          </div>
          <div class="card-body">
            <b>Date:</b> {{ order.date }}<br />
            <b>Total:</b> ${{ order.total }}<br />
            <table class="table table-bordered
              table-striped text-center mt-3">
              <thead>
                <tr>
                  <th scope="col">Item ID</th>
                  <th scope="col">Movie</th>
                  <th scope="col">Price</th>
                  <th scope="col">Quantity</th>
                </tr>
              </thead>
              <tbody>
                {% for item in order.item_set.all %}
                <tr>
                  <td>{{ item.movie.id }}</td>
                  <td>
                    <a class="link-dark"
                      href="{% url 'movies.show'
                      id=item.movie.id %}">
                      {{ item.movie.name }}
                    </a>
                  </td>
                  <td>${{ item.movie.price }}</td>
                  <td>{{ item.quantity }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'dase.html' %}
{% block content %}
<div class="p-3 mt-4">
  <div class="container" style="padding-top: 80px;">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow p-3 mb-4 rounded">
          <div class="card-body">
            <h2>Sign Up</h2>
            <hr />
            <form method="POST">
              {% csrf_token %}
              {{ template_data.form.as_p }}
              <button type="submit"
                class="btn bg-dark text-white">Sign Up
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}